# Generated by Django 5.2 on 2025-04-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_id', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('client', models.CharField(default='N/A', max_length=100)),
                ('total_design', models.PositiveIntegerField()),
                ('previously_done', models.PositiveIntegerField()),
                ('today_target', models.PositiveIntegerField()),
                ('status', models.CharField(default='In Progress', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('designer1', models.CharField(max_length=100)),
                ('designer1_target', models.PositiveIntegerField()),
                ('designer1_done', models.PositiveIntegerField()),
                ('designer2', models.CharField(max_length=100)),
                ('designer2_target', models.PositiveIntegerField()),
                ('designer2_done', models.PositiveIntegerField()),
                ('designer3', models.CharField(max_length=100)),
                ('designer3_target', models.PositiveIntegerField()),
                ('designer3_done', models.PositiveIntegerField()),
                ('designer4', models.CharField(max_length=100)),
                ('designer4_target', models.PositiveIntegerField()),
                ('designer4_done', models.PositiveIntegerField()),
                ('done_today', models.PositiveIntegerField()),
                ('design_left', models.IntegerField()),
                ('total_done', models.PositiveIntegerField()),
            ],
        ),
    ]
